version: "3.7"

services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: ${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/mariadb:/var/lib/mysql
    networks:
      - glpi-net

  glpi:
    image: diouxx/glpi:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      GLPI_DB_HOST: mariadb
      GLPI_DB_USER: glpi
      GLPI_DB_PASSWORD: ${APP_PASSWORD}
      GLPI_DB_NAME: glpi
      GLPI_DB_CHARSET: utf8mb4
      GLPI_INSTALL_MODE: auto

    volumes:
      - ${APP_DATA_DIR}/glpi:/var/www/html
    networks:
      - glpi-net

  app_proxy:
    image: getumbrel/app-proxy:v0.1.1
    restart: on-failure
    environment:
      APP_HOST: glpi
      APP_PORT: 80

networks:
  glpi-net:
    driver: bridge