version: "3.7"

services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/mariadb:/var/lib/mysql
    networks:
      - glpi-net

  glpi:
    image: diouxx/glpi:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      GLPI_DB_HOST: mariadb
      GLPI_DB_USER: glpi
      GLPI_DB_PASSWORD: ${MYSQL_PASSWORD}
      GLPI_DB_NAME: glpi
      GLPI_DB_CHARSET: utf8mb4
      GLPI_INSTALL_MODE: auto
    ports:
      - "8080:80"
    volumes:
      - ${APP_DATA_DIR}/glpi:/var/www/html
    networks:
      - glpi-net

networks:
  glpi-net:
    driver: bridge